import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { api } from "../../../services/api";
import Footer from "../../components/Footer";
import styles from "./login.module.scss";

import { Input, Button, Form, Checkbox, Modal, Select } from "antd";
import { LeftOutlined } from "@ant-design/icons";
import "antd/dist/antd.css";
import { Header } from "../../components/Header";
import { useCallback, useState } from "react";
import onNotification from "../../components/Notificacao/Notificacao";

export default function Login() {
  const router = useRouter();

  const [modalregistro, setModalRegistro] = useState(false);

  const [login] = Form.useForm();
  const [cadastro] = Form.useForm();
  const [form] = Form.useForm();

  const onFinish = (values: any) => {
    console.log("Success:", values);
  };

  const onFinishFailed = (errorInfo: any) => {
    console.log("Failed:", errorInfo);
  };

  // const mostraModalRegistro = () => {
  //   setModalRegistro(true);
  // };

  const cadastraUsuario = useCallback(async (form: any) => {
    try {
      await api.post("/usuarios", form);
      onNotification("success", {
        message: "Ok!",
        description: "Usuário cadastrado com sucesso",
      });
      setModalRegistro(false);
      cadastro.resetFields();
    } catch (err) {
      console.log("erro");
      onNotification("error", {
        message: "Erro!",
        description: "Erro ao cadastrar usuário",
      });
      setModalRegistro(false);
    }
  }, []);

  const handleOk = (values) => {
    setModalRegistro(false);
    form.resetFields();
    console.log(values);
  };

  const handleCancel = () => {
    setModalRegistro(false);
    // form.resetFields();
  };

  const { Option } = Select;

  return (
    <>
      <Head>
        <title>Biblioteca Seap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <Header login={true} />
      <main className={styles.main}>
        <div className={styles.card}>
          <Form
            layout="vertical"
            name="login"
            form={login}
            labelCol={{ span: 10 }}
            wrapperCol={{ span: 24 }}
            initialValues={{ remember: true }}
            onFinish={onFinish}
            onFinishFailed={onFinishFailed}
            autoComplete="off"
          >
            <h2>Login</h2>
            <Form.Item
              label="Email"
              name="email"
              rules={[{ required: true, message: "Informe seu email!" }]}
            >
              <Input />
            </Form.Item>

            <Form.Item
              label="Senha"
              name="Senha"
              rules={[{ required: true, message: "Informe sua senha!" }]}
            >
              <Input.Password />
            </Form.Item>

            <Form.Item
              name="lembrar"
              valuePropName="checked"
              // wrapperCol={{ offset: 8, span: 16 }}
            >
              <Checkbox>Lembrar-me</Checkbox>
            </Form.Item>

            <Form.Item
            // wrapperCol={{ offset: 8, span: 16 }}
            >
              <Link href={`/home`}>
                <Button
                  // type="primary"
                  htmlType="submit"
                  style={{
                    background: "#04d361",
                    color: "#fff",
                    width: "100%",
                    marginBottom: -50,
                  }}
                >
                  Entrar
                </Button>
              </Link>
            </Form.Item>

            <Link href={``}>
              <Button
                // type="primary"
                // htmlType="submit"
                style={{
                  // background: "#04d361",
                  // color: "#fff",
                  width: "100%",
                }}
                onClick={() => setModalRegistro(true)}
              >
                Registrar
              </Button>
            </Link>

            {/* <Link href={``}>Registrar</Link> */}
          </Form>
        </div>
      </main>

      <Footer />

      <Modal
        title="Cadastro de Usuário"
        visible={modalregistro}
        onOk={handleOk}
        onCancel={handleCancel}
        width={600}
        footer={[]}
      >
        <Form
          layout="vertical"
          name="cadastro"
          form={cadastro}
          labelCol={{ span: 10 }}
          wrapperCol={{ span: 24 }}
          initialValues={{ remember: true }}
          onFinish={cadastraUsuario}
          // onFinishFailed={onFinishFailed}
          autoComplete="off"
        >
          <Form.Item
            label="Nome"
            name="nome"
            rules={[{ required: true, message: "Informe seu nome!" }]}
          >
            <Input />
          </Form.Item>

          <Form.Item
            label="Email"
            name="email"
            rules={[{ required: true, message: "Informe seu email!" }]}
          >
            <Input />
          </Form.Item>

          <Form.Item
            label="Senha"
            name="senha"
            rules={[{ required: true, message: "Informe sua senha!" }]}
          >
            <Input.Password />
          </Form.Item>

          <Form.Item
            label="Perfil"
            name="perfil"
            rules={[{ required: true, message: "Informe seu perfil!" }]}
          >
            <Select
            // defaultValue="usuario"
            // style={{ width: 120 }}
            // onChange={handleChange}
            >
              <Option value="usuario">Usuario</Option>
              <Option value="administrador">Administrador</Option>
            </Select>
          </Form.Item>

          <Form.Item
          // wrapperCol={{ offset: 8, span: 16 }}
          >
            <Button
              // type="primary"
              htmlType="submit"
              style={{
                background: "#04d361",
                color: "#fff",
                width: "100%",
                marginBottom: -50,
              }}
            >
              Cadastrar
            </Button>
          </Form.Item>
        </Form>
      </Modal>
    </>
  );
}
