/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import { useCallback, useState, useContext } from "react";
import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { api } from "../../../services/api";
import Footer from "../../components/Footer";
import styles from "./login.module.scss";
// import Logo from "../../../public/logo.svg";

import {
  Input,
  Button,
  Form,
  Checkbox,
  Modal,
  Select,
  Spin,
  Divider,
  Row,
  Col,
} from "antd";

import { LeftOutlined } from "@ant-design/icons";
import "antd/dist/antd.css";
import { Header } from "../../components/Header";
import onNotification from "../../components/Notificacao/Notificacao";
import { AutenticadoContext } from "../../context/AuthContext";

// import MenuLateral from '../../components/template/Menu/NavBarVisita'
import { CalendarOutlined } from "@ant-design/icons";

import Background from "../../assets/image/back-seap-online-web.png";
import Logo from "../../assets/image/seap-online-logo.png";
import LogoGoverno from "../../assets/image/logo-governo.png";
// import { validateMessages2, CpfRequired } from '../../utils/ValidatorFields'
// import { rowProps } from '../../utils/FormUtils'
const FormItem = Form.Item;

// import { useDadosPessoaisVisita } from '../../hooks/dadosPessoaisVisita'
import MaskedInput from "antd-mask-input";
// import api, { apiVisitas } from '../../services/api'
// import onNotification from '../../components/notification/Notification'
import { AxiosResponse } from "axios";
// import { setCookie } from 'nookies'

const PreSenha = () => {
  // const { getDadosVisita } = useDadosPessoaisVisita()
  const [loading, setLoading] = useState(false);
  const [form] = Form.useForm();
  const router = useRouter();
  // const { Title } = Typography;

  // const save = async (data) => {
  //   setLoading(true)
  //   try {
  //     const response: AxiosResponse = await apiVisitas.get(
  //       'visita-virtual-service/visitantes',
  //       {
  //         params: {
  //           cpf: data.cpf.replaceAll('.', '').replace('-', ''),
  //           matricula: data.matricula
  //         }
  //       }
  //     )
  //     getDadosVisita({
  //       matricula: response.data.idPessoaVisitante,
  //       nomeVisita: response.data.nome
  //     })

  //     console.log(response.headers)
  //     setCookie(
  //       undefined,
  //       'agendar-visita-token',
  //       response?.headers?.authorization?.replaceAll('Bearer ', ''),
  //       {
  //         maxAge: 60 * 60 * 24 * 30,
  //         path: '/'
  //       }
  //     )

  //     router.push(`/visitas/menuTelaDeVisita`)
  //   } catch (error: any) {
  //     getDadosVisita({})
  //     setLoading(true)
  //     if (error?.response?.status === 500) {
  //       setLoading(false)
  //       return onNotification('error', {
  //         message: 'ERROR!',
  //         description: error.response.data.userMessage
  //       })
  //     }
  //     onNotification('error', {
  //       message: 'ERROR!',
  //       description: 'Erro ao Encontrar CPF ou Matricula'
  //     })
  //     setLoading(false)
  //   }
  // }

  return (
    <>
      <Head>
        <title>Biblioteca Seap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/seap-juris/logo.png" />
      </Head>

      <Header login={false} />
      <main className={styles.main}>
        <img
          width={150}
          src="/seap-juris/logo.svg"
          style={{
            marginBottom: "3rem",
          }}
        />
        <div className={styles.card}>
          <Spin tip="Carregando..." spinning={loading}>
            <h1 style={{ textAlign: "center", margin: 0, padding: 0 }}>
              Solicitar Visita Presencial
            </h1>
            <Divider />
            <Form
              form={form}
              layout="vertical"
              // onFinish={save}
              // validateMessages={validateMessages2}
            >
              <Row
              // {...rowProps}
              >
                <Col span={24}>
                  <FormItem
                    name="matricula"
                    label="Matricula"
                    rules={[{ required: true }]}
                    hasFeedback
                    // style={{ maxWidth: '300px', width: '300px' }}
                  >
                    <Input />
                  </FormItem>
                </Col>
              </Row>
              <Row
              // {...rowProps}
              >
                <Col span={24}>
                  <FormItem
                    name="cpf"
                    label="CPF"
                    // rules={CpfRequired}
                    hasFeedback
                  >
                    <MaskedInput
                      mask="000.000.000-00"
                      // className="ant-input-login"
                    />
                    {/* <Input /> */}
                  </FormItem>
                </Col>
              </Row>
              <Button
                // type="primary"
                htmlType="submit"
                style={{
                  background: "#000b6b",
                  color: "#fff",
                  width: "100%",
                  marginBottom: -50,
                }}
              >
                ENTRAR
              </Button>
            </Form>
          </Spin>
        </div>
      </main>

      <Footer />
    </>
  );
};

export default PreSenha;
