/* eslint-disable @next/next/no-img-element */
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { api } from "../../../services/api";

import styles from "../../styles/Locacoes.module.scss";
import Link from "next/link";
import Footer from "../../components/Footer";
import Head from "next/head";

// type Livro = {
//   id: number;
//   titulo: string;
//   descricao: string;
//   dataCadastro: string;
//   locado: string;
//   url: string;
// };

type Livros = {
  id: number;
  titulo: string;
  sub: string;
  descricao: string;
  dataCadastro: string;
  dataRetirada: string;
  locado: string;
  file: {
    url: string;
  };
};

// type LivroProps = {
//   livro: Livro;
// };

export default function Locacoes() {
  const [livros, setLivros] = useState([]);

  useEffect(() => {
    buscaLivros();
  }, []);

  const buscaLivros = async () => {
    const response = await api.get("livros", {
      params: {
        _limit: 10,
        _sort: "dataRetirada",
        _order: "desc",
      },
    });

    setLivros(response.data);
    console.log(response.data);
  };

  // const router = useRouter();

  return (
    <>
      <Head>
        <title>Biblioteca Seap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.homepage}>
        <h2>Ultimas Locações</h2>
        <section className={styles.livrosRecentes}>
          <ul>
            {livros.map((item: Livros) => {
              // eslint-disable-next-line react/jsx-key
              return (
                <Link href={`/livros/${item.id}`} key={item.id}>
                  <li>
                    <img
                      src={item.file.url}
                      alt="foto"
                      width={70}
                      height={70}
                      // objectFit="cover"
                    />
                    <div className={styles.livrosDetalhes}>
                      <span>{item.titulo}:</span>
                      <p>{item.sub}</p>
                    </div>
                    <div
                      className={styles.livrosDetalhes}
                      style={{
                        borderLeft: `1px solid var(--gray-100)`,
                        paddingLeft: "2rem",
                      }}
                    >
                      <span>Data de retirada:</span>
                      <p>{item.dataRetirada}</p>
                    </div>
                    <div
                      className={styles.livrosDetalhes}
                      style={{
                        borderLeft: `1px solid var(--gray-100)`,
                        paddingLeft: "2rem",
                      }}
                    >
                      <span>Data para devolução:</span>
                      <p>{item.dataRetirada}</p>
                    </div>
                  </li>
                </Link>
              );
            })}
          </ul>
        </section>
      </div>
      <Footer />
    </>
  );
}
