import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { api } from "../../../services/api";
import Footer from "../../components/Footer";
import styles from "./livros.module.scss";

import { Input, Button, Tooltip } from "antd";
import { LeftOutlined } from "@ant-design/icons";
import "antd/dist/antd.css";

import { Menu } from "../../components/Menu";
import { Header } from "../../components/Header";

type Livro = {
  id: number;
  titulo: string;
  sub: string;
  descricao: string;
  dataCadastro: string;
  locado: string;
  url: string;
};

type LivroProps = {
  livro: Livro;
};

export default function Livro({ livro }: LivroProps) {
  const router = useRouter();

  if (router.isFallback) {
    <p>Carregando...</p>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Biblioteca Seap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <Header login={false} />
      <div className={styles.wrapper}>
        <Menu />
        <main>
          <div className={styles.livro}>
            <h1>Detalhes do Livro</h1>
            <section className={styles.detalhes}>
              <Tooltip placement="left" title={"Voltar"} color={"#04d361"}>
                <Link href={`/home`}>
                  <Button type="primary">
                    <LeftOutlined />
                  </Button>

                  {/* <button type="button">
              <img src="/seta.png" alt="" />
            </button> */}
                </Link>
              </Tooltip>
              <Image
                src="/1.webp"
                alt="foto"
                width={700}
                height={160}
                layout="responsive"
                objectFit="cover"
                className={styles.img}
              />
              <header>
                <h1>
                  {livro.titulo}: {livro.sub}
                </h1>
              </header>
              <div className={styles.descricao}>
                <span>{livro.descricao}</span>
              </div>
            </section>
          </div>
          <Footer />
        </main>
      </div>
    </div>
  );
}

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [],
    fallback: "blocking", // gera a pagina estatica na camada do nodejs. Melhor opção para seo (pesquisas). so mostra a pagina depois de tudo carregado
    // fallback: "true", // gera a pagina estatica do lado do cliente
  };
};

export const getStaticProps: GetStaticProps = async (ctx) => {
  const { id }: any = ctx.params;

  const { data } = await api.get(`/livros/${id}`);

  const livro = {
    id: data.id,
    titulo: data.titulo,
    sub: data.sub,
    descricao: data.descricao,
    dataCadastro: data.dataCadastro,
    locado: data.locado,
    url: data.file.url,
  };

  return {
    props: { livro },
    revalidate: 60 * 60 * 24, // 24 horas
  };
};
