/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { api } from "../../services/api";
import { Header } from "../components/Header";
import styles from "../styles/Home.module.scss";

type Livros = {
  id: number;
  titulo: string;
  descricao: string;
  dataCadastro: string;
  file: {
    url: string;
  };
};

const Home: NextPage = () => {
  const [livros, setLivros] = useState([]);

  useEffect(() => {
    buscaLivros();
  }, []);

  const buscaLivros = async () => {
    const response = await api.get("livros", {
      params: {
        _limit: 7,
        _sort: "titulo",
        _order: "desc",
      },
    });

    setLivros(response.data);
    console.log(response.data);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Biblioteca Seap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.homepage}>
        <section className={styles.livrosRecentes}>
          <ul>
            {livros.map((item: Livros) => {
              // eslint-disable-next-line react/jsx-key
              return (
                <li key={item.id}>
                  <img
                    src={item.file.url}
                    alt="foto"
                    width={70}
                    height={70}
                    // objectFit="cover"
                  />
                  <br />
                  <div className={styles.livrosDetalhes}>
                    <span>{item.titulo}:</span>
                    <p>{item.descricao}</p>
                  </div>
                </li>
              );
            })}
          </ul>
        </section>

        {/* <section className={styles.listaLivros}></section> */}
      </div>

      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        > */}
        Secretaria de Administração Penitenciária - SEAP
        {/* <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span> */}
        {/* </a> */}
      </footer>
    </div>
  );
};

export default Home;
